name: CI-CD Production Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  # 1. SAST (Análise Estática)
  sast-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bandit & Pip-Audit
        run: |
          pip install bandit pip-audit
          bandit -r . -ll -ii -s B104
          # Adicione o '-r' para focar apenas no seu requirements.txt
          pip-audit -r requirements.txt

  # 2. BUILD (Construção do ambiente)
  build:
    needs: sast-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build dos Containers
        run: docker compose up -d --build
  
  # 3. TEST (Integração Contínua)
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rodar Testes Automatizados
        run: |
          # Re-sobe o container se necessário ou conecta ao existente
          docker compose up -d
          docker compose exec -T web pip install pytest
          docker compose exec -T web pytest tests/test_funcional.py
  

  # 4. DAST (Análise Dinâmica)
  dast-analysis:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - name: Rodar ZAP
        run: |
          mkdir -p $(pwd)/zap_results
          docker run --network host -v $(pwd)/zap_results:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://localhost:5000 \
            -r /zap/wrk/zap-report.html -J /zap/wrk/zap-report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: zap-security-reports
          path: zap_results/zap-report.*